
spring:
  mustache:
    suffix: .html
    expose-session-attributes: true

  jpa:
    hibernate:
      ddl-auto: update

  mvc:
    hiddenmethod:
      filter:
        enabled: true

logging:
    level:
      org.springframework.web: debug

server:
  port: 80



































