
spring:
  mustache:
    suffix: .html
    expose-session-attributes: true

  datasource:
    url: jdbc:mariadb://database-2.ccw4mmoyfzrt.ap-northeast-2.rds.amazonaws.com:3306/kwsinsa
    username: alex1461
    password: Alex33942540!
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto:

  mvc:
    hiddenmethod:
      filter:
        enabled: true


































